Update shell scripts

diff --git a/bin/commonmark b/bin/commonmark
--- a/bin/commonmark
+++ b/bin/commonmark
@@ -1,16 +1,40 @@
-#!/usr/bin/env python3
-from commonmark import commonmark
-import sys
+#!/bin/sh
+set -euf
 
+run_cmark() {
+    case "${1-}" in
+        -*) set -- ./"$1" ;;
+    esac
+    command cmark "$@"
+}
 
-def main():
-    if len(sys.argv) <= 1:
-        print(commonmark(sys.stdin.read()), end="")
-        return
-    for name in sys.argv[1:]:
-        with open(name) as f:
-            print(commonmark(f.read()), end="")
+pulldown_cmark() {
+    pulldown-cmark -- "$@"
+}
 
+case "${1-}" in
+    -h|--help)
+        printf '%s\n' "usage: $(basename "$0") <file>..."
+        exit
+        ;;
+    --)
+        shift
+        ;;
+esac
 
-if __name__ == "__main__":
-    main()
+unset target
+if command -v cmark > /dev/null; then
+    target=run_cmark
+elif command -v pulldown-cmark > /dev/null; then
+    target=pulldown_cmark
+else
+    printf >&2 '%s\n' 'error: missing (pulldown-)cmark'
+    exit 1
+fi
+
+if [ "$#" -eq 0 ]; then
+    $target
+fi
+for f do
+    $target "$f"
+done
diff --git a/bin/paragraph-join b/bin/paragraph-join
--- a/bin/paragraph-join
+++ b/bin/paragraph-join
@@ -1,9 +1,25 @@
-#!/usr/bin/env python3
-import re
-import sys
-
-if len(sys.argv) > 1:
-    file = open(sys.argv[1])
-else:
-    file = sys.stdin
-print(re.sub(r"(.)\n(.)", r"\1 \2", file.read()), end="")
+#!/bin/sh
+set -euf
+if [ "$#" -gt 1 ]; then
+    printf >&2 '%s\n' "error: unexpected argument"
+    exit 1
+fi
+exec awk -- '
+    function end() {
+        if (any) print ""
+        any = 0
+    }
+    /./ {
+        if (any) printf " "
+        printf "%s", $0
+        any = 1
+        next
+    }
+    {
+        end()
+        print
+    }
+    END {
+        end()
+    }
+' "$@"
