Refactor scripts

diff --git a/bin/scrot b/bin/scrot
--- a/bin/scrot
+++ b/bin/scrot
@@ -3,41 +3,76 @@
 # License: GNU GPL version 3 or later
 set -euf
 
-unset fullwidth fullheight width height posx posy right bottom
-unset line im_args fullsize scrot
-fullwidth=0
-fullheight=0
+dir=$(dirname "$0")
+path=:$PATH:
+case "$path" in
+    *:$dir:*) path=${path%%:$dir:*}:${path#*:$dir:} ;;
+esac
+path=${path#:}
+path=${path%:}
+if ! scrot=$(PATH=$path command -v scrot); then
+    printf >&2 '%s\n' 'error: missing scrot'
+    exit 1
+fi
+
 IFS='
 '
+fullwidth=0
+fullheight=0
+im_args=
+
+handle_monitor() {
+    local width=$1
+    local height=$2
+    local posx=$3
+    local posy=$4
+    local right=$((posx+width))
+    local bottom=$((posy+height))
+    [ "$right" -le "$fullwidth" ] || fullwidth=$right
+    [ "$bottom" -le "$fullheight" ] || fullheight=$bottom
+}
+
 for line in $(~/scripts/monitor-utils.sh monitors); do
-    width=$(printf '%s\n' "$line" | cut -f2)
-    height=$(printf '%s\n' "$line" | cut -f3)
-    posx=$(printf '%s\n' "$line" | cut -f4)
-    posy=$(printf '%s\n' "$line" | cut -f5)
-    right=$((posx+width))
-    bottom=$((posy+height))
-    [ "$right" -gt "$fullwidth" ] && fullwidth=$right
-    [ "$bottom" -gt "$fullheight" ] && fullheight=$bottom
+    handle_monitor $(printf '%s\n' "$line" | tr '\t' '\n')
 done
 
-im_args=
-for line in $(~/scripts/monitor-utils.sh monitors); do
-    width=$(printf '%s\n' "$line" | cut -f2)
-    height=$(printf '%s\n' "$line" | cut -f3)
-    posx=$(printf '%s\n' "$line" | cut -f4)
-    posy=$(printf '%s\n' "$line" | cut -f5)
+handle_monitor() {
+    local width=$1
+    local height=$2
+    local posx=$3
+    local posy=$4
     if [ "$posy" -gt 0 ]; then
-        im_args="$im_args -draw 'rectangle $posx,0"
-        im_args="$im_args $((posx+width-1)),$((posy-1))'"
+        local p1=$posx,0
+        local p2=$((posx+width-1)),$((posy-1))
+        im_args="$im_args -draw 'rectangle $p1 $p2'"
     fi
     if [ "$((posy+height))" -lt "$fullheight" ]; then
-        im_args="$im_args -draw 'rectangle $posx,$((posy+height))"
-        im_args="$im_args $((posx+width-1)),$((fullheight-1))'"
+        local p1=$posx,$((posy+height))
+        local p2=$((posx+width-1)),$((fullheight-1))
+        im_args="$im_args -draw 'rectangle $p1 $p2'"
     fi
+}
+
+for line in $(~/scripts/monitor-utils.sh monitors); do
+    handle_monitor $(printf '%s\n' "$line" | tr '\t' '\n')
 done
 
 fullsize=${fullwidth}x${fullheight}
-scrot=$(PATH=/usr/bin:/usr/local/bin command -v scrot)
-"$scrot" -e "\
-if [ \"\\\$(identify -format '%%wx%%h' '\$f')\" = \"$fullsize\" ]; then \
-mogrify -fill white $im_args -alpha off '\$f'; fi" "$@"
+
+dir=$(dirname "$0")
+path=:$PATH:
+case "$path" in
+    *:$dir:*)
+        path=${path%:$dir:*}:${path#*:$dir:}
+        ;;
+esac
+path=${path#:}
+path=${path%:}
+scrot=$(PATH=$path command -v scrot)
+
+"$scrot" -e "$(cat << EOF
+if [ "\$(identify -format '%%wx%%h' '\$f')" = "$fullsize" ]; then
+    mogrify -fill white $im_args -alpha off '\$f'
+fi
+EOF
+)" "$@"
diff --git a/bin/urxvt b/bin/urxvt
--- a/bin/urxvt
+++ b/bin/urxvt
@@ -3,8 +3,18 @@
 # License: GNU GPL version 3 or later
 set -euf
 
-unset monitor_field monitor_value properties prop_mono prop_hidpi
-unset line value args cmd name title state arg i urxvt
+dir=$(dirname "$0")
+path=:$PATH:
+case "$path" in
+    *:$dir:*) path=${path%%:$dir:*}:${path#*:$dir:} ;;
+esac
+path=${path#:}
+path=${path%:}
+if ! urxvt=$(PATH=$path command -v urxvt); then
+    printf >&2 '%s\n' 'error: missing urxvt'
+    exit 1
+fi
+
 case "${URXVT_MONITOR-}" in
     "")
         monitor_field=1
@@ -42,6 +52,8 @@ esac
 
 args=
 cmd=
+unset name
+unset title
 state=
 i=0
 
@@ -73,20 +85,34 @@ for arg do
     esac
 done
 
+[ -n "$cmd" ] || cmd=$(awk -vFS=: '
+    BEGIN {
+        uid = ARGV[2]
+        ARGC = 2
+    }
+
+    $3 == uid {
+        print $7
+    }
+' /etc/passwd "$(id -u)")
 : ${cmd:=bash}
+
+colors_sh=~/scripts/"set-urxvt-colors.sh"
 if [ -n "$prop_mono" ]; then
     if command -v monoterm > /dev/null; then
         cmd="monoterm -b $cmd"
     fi
-elif [ -z "${KEEPCOLORS-}" ] && [ -x ~/scripts/set-urxvt-colors.sh ]; then
-    cmd="~/scripts/set-urxvt-colors.sh $cmd"
+elif [ -z "${KEEPCOLORS-}" ] && [ -x "$colors_sh" ]; then
+    cmd="\"\$colors_sh\" $cmd"
+fi
+unset KEEPCOLORS
+
+hidpi_sh=~/scripts/hidpi.sh
+if [ -n "$prop_hidpi" ] && [ -x "$hidpi_sh" ]; then
+    cmd="\"\$hidpi_sh\" $cmd"
 fi
 
-if [ -n "$prop_hidpi" ] && [ -x ~/scripts/hidpi.sh ]; then
-    cmd="~/scripts/hidpi.sh $cmd"
-fi
-
-if [ -z "${name-}" ]; then
+if [ -z "${name+x}" ]; then
     name=Rxvt
     if [ -n "$prop_mono" ]; then
         name="$name.mono"
@@ -107,6 +133,5 @@ if [ -z "$prop_mono" ] && [ -n "$prop_hidpi" ]; then
 fi
 
 : ${title=urxvt}
-urxvt=$(PATH=/usr/bin:/usr/local/bin command -v urxvt)
 eval "set -- $args -e $cmd"
 exec "$urxvt" -name "$name" -title "$title" "$@"
